/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "secondary": "#006c49",
        "secondary-container": "#6cf8bb",
        "inverse-primary": "#b4c5ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#eaf1ff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#dbe1ff",
        "tertiary": "#784b00",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "on-primary-container": "#eeefff",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#ffeedd",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#00714d",
        "secondary-fixed": "#6ffbbe",
        "outline": "#737686",
        "on-primary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary": "#ffffff",
        "primary-container": "#2563eb",
        "surface-container-low": "#eff4ff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-surface": "#213145",
        "on-surface-variant": "#434655",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "primary": "#004ac6",
        "tertiary-container": "#996100",
        // Dark theme tokens
        "canvas": "#0B0F19",
        "canvas-card": "#131B2E",
        "canvas-card-elevated": "#1E293B",
        "canvas-card-subtle": "#172238",
        "card-border": "#2A374F",
        "brand-primary": "#3B82F6",
        "brand-primary-hover": "#2563EB",
        "brand-primary-light": "#60A5FA",
        "text-high": "#F8FAFC",
        "text-medium": "#94A3B8",
        "text-muted": "#64748B",
        "status-emerald": "#10B981",
        "status-emerald-text": "#34D399",
        "status-emerald-bg": "rgba(16, 185, 129, 0.15)",
        "status-red": "#EF4444",
        "status-red-text": "#F87171",
        "status-red-bg": "rgba(239, 68, 68, 0.15)",
        "status-amber": "#F59E0B",
        "status-amber-text": "#FBBF24",
        "status-amber-bg": "rgba(245, 158, 11, 0.15)",
        "status-blue": "#3B82F6",
        "status-blue-text": "#93C5FD",
        "status-blue-bg": "rgba(59, 130, 246, 0.15)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.75rem",
        "margin-tablet": "2rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "margin-desktop": "3rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "numeric-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "display-lg-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "numeric-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    }
  },
  plugins: []
};
